apiVersion: apps/v1
kind: Deployment
metadata:
  name: litehat
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: litehat
  template:
    metadata:
      labels:
        app: litehat
    spec:
      containers:
        - name: litehat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
